version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  web:
    build: django_api_keys/
    command: python manage.py runserver 0.0.0.0:8000
    container_name: api-key-proxy-web
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword

  mitm:
    build: mitm/
    command: mitmdump
    ports:
      - "8080:8080"
    depends_on:
      - web
    volumes:
      - ./mitm:/home/mitmproxy/.mitmproxy
  